### ISSUE TITLE
encoding error not visible in TopicsExplorer

### ISSUE THREAD

**Issue by MHuberFaust** [DARIAH-DE/TopicsExplorer#57]
encoding Errors produced by read_files() are not visible in TopicsExplorer.

**Comment by severinsimmler** [comment]
How exactly did that turn out? And what exactly do you mean by `read_files()`? Because it is a web application, the hard disk cannot be accessed directly for security reasons. The user has to select the files, which are then fetched by Flask in binary format and decoded here with UTF-8:

https://github.com/DARIAH-DE/TopicsExplorer/blob/cdefcdc64ef8fafeded59d0c975f03f71a06a14c/application/modeling.py#L70

**Comment by MHuberFaust** [comment]
it stopped at "reading files" (or sth like that), flower still turning, just no progress.
I tried to circumvent the problem by using the notebook... that's why I figured it had something to do with read_files().
So it probably needs an exception to test on correct encoding

**Comment by severinsimmler** [comment]
Do you have any details on the files? In v0.1.6, the file name currently being processed is displayed on the GUI. Since the text files are sent to localhost, this can take a while for large files. The entire workflow (including reading files) is in a large `try` block. This means that if an error should occur, this will always be indicated. If it just seems to freeze, everything still works correctly.

If you have the data (or the contact details of the person affected), I would try to reproduce it with the developer version and can probably tell you more.
